### PR TITLE
Several bug fixes and improvements when dealing with containers

### PR DESCRIPTION
**Pull request by jfilak**
This pull request is necessary for the future enhancements of ABRT.

### CODE REVIEW

**Comment by jfilak** [comment]
One new introduced test is not finished. I will fix it ASAP.

**Comment by jfilak** [comment]
Correction, the test is finished but the patch that is supposed to make it better was not tested.

**Comment by jfilak** [comment]
The PR is ready to be reviewed and eventually merged.

**Comment by jfilak** [comment]
Oh snap! The PR still fails to build, while my local build ran without a warning. What's the problem now? We need to make build results publicly available.

**Comment by jfilak** [comment]
Note: the PR must update CHANGELOG too.

**Comment by mhabrnal** [comment]
Test process_has_own_root fails, but it works on my VMs.

```
DEBUG: 112. proc_helpers.at:1048: testing process_has_own_root ...
DEBUG: ./proc_helpers.at:1048: $LIBTOOL --mode=link $CC $CFLAGS $LDFLAGS -o process_has_own_root process_has_own_root.c $LIBS
DEBUG: stderr:
DEBUG: In file included from /usr/include/assert.h:35:0,
DEBUG:                  from /builddir/build/BUILD/libreport-2.9.0.17.g8824a/src/include/internal_libreport.h:23,
DEBUG:                  from /builddir/build/BUILD/libreport-2.9.0.17.g8824a/tests/helpers/testsuite.h:88,
DEBUG:                  from proc_helpers.at:1049:
DEBUG: /usr/include/features.h:331:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
DEBUG:  #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
DEBUG:     ^~~~~~~
DEBUG: stdout:
DEBUG: libtool: link: gcc -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -std=gnu99 -Wall -Wwrite-strings -I/builddir/build/BUILD/libreport-2.9.0.17.g8824a/tests/helpers -I/builddir/build/BUILD/libreport-2.9.0.17.g8824a/src/include -I/builddir/build/BUILD/libreport-2.9.0.17.g8824a/src/lib -I/builddir/build/BUILD/libreport-2.9.0.17.g8824a/src/gtk-helpers -D_GNU_SOURCE -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -DDEFAULT_DUMP_DIR_MODE=0x1A0 -Wl,-z -Wl,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o .libs/process_has_own_root process_has_own_root.c  /builddir/build/BUILD/libreport-2.9.0.17.g8824a/src/gtk-helpers/.libs/libreport-gtk.so -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 /builddir/build/BUILD/libreport-2.9.0.17.g8824a/src/lib/.libs/libreport-web.so -lcurl -lproxy -lxml2 -ljson-c -lxmlrpc -lxmlrpc_util -lxmlrpc_client /builddir/build/BUILD/libreport-2.9.0.17.g8824a/src/lib/.libs/libreport.so -ltar -lsystemd -lgobject-2.0 -lglib-2.0 -laugeas -lsatyr -pthread
DEBUG: ./proc_helpers.at:1048: $PRE_AT_CHECK ./process_has_own_root
DEBUG: stderr:
DEBUG: failed to open '/proc/[pid]/mountinfo': No such file or directory
DEBUG: failed to open '/proc/[pid]/mountinfo': Permission denied
DEBUG: Mountinfo line does not have enough fields 0
DEBUG: cannot get mount info for [pid]'s /
DEBUG: Made-up mountinfo created in /tmp/libreport.testsuite.pid.VJkmZI
DEBUG: Mountinfo line does not have enough fields 0
DEBUG: cannot get mount info for [pid]'s /
DEBUG: Going to copy /proc/1/mountinfo to /tmp/libreport.testsuite.pid.VJkmZI
DEBUG: Copying /proc/1/mountinfo to /tmp/libreport.testsuite.pid.VJkmZI
DEBUG: Copied /proc/1/mountinfo to /tmp/libreport.testsuite.pid.VJkmZI
DEBUG: findmnt -r -n -o VFS-OPTIONS,OPT-FIELDS -T / : (null)
DEBUG: /builddir/build/BUILD/libreport-2.9.0.17.g8824a/tests/testsuite.dir/at-groups/112/test-source: line 175: 25029 Segmentation fault      (core dumped) $PRE_AT_CHECK ./process_has_own_root
DEBUG: stdout:
DEBUG: ./proc_helpers.at:1048: exit code was 139, expected 0
DEBUG: 112. proc_helpers.at:1048: 112. process_has_own_root (proc_helpers.at:1048): FAILED (proc_helpers.at:1048)
```

**Comment by jfilak** [comment]
Could you please, check that `findmnt` is available in the build root? It is shipped by the `util-linux` package. I was under the impression the package must be installed on all systems. I probably need to add it to BRs and Rs.

**Comment by mhabrnal** [comment]
retest this please

**Comment by mhabrnal** [comment]
findmnt is available in the buildroot

```
# mock -r fedora-25-x86_64 --configdir=/etc/mock/libreport/ --shell "rpm -qf $(which findmnt)"
util-linux-2.28.2-1.fc25.x86_64
```

**Comment by jfilak** [comment]
Good news, the build fails in my mock too. So I can debug it and fix it.

**Comment by jfilak** [comment]
If the PR builds, please review it. I've added 2 new commits - 1. fixes for the testsuite, 2. update to changelog.  Every PR should include CHANGELOG.md!

**Comment by mhabrnal** [comment]
Looks good to me, especially an idea with CHANGELOG.md.

**Pull request merged**
