### PR TITLE
reporter-bugzilla: Fix password prompt in client/server mode

### PR DESCRIPTION
**Pull request by msrb**
Fixes: rhbz#2172891

Signed-off-by: Michal Srb <michal@redhat.com>

### CODE REVIEW

**Comment by msrb** [comment]
@michalfabik @mgrabovsky PTAL ;)

**Comment by mgrabovsky** [comment]
Why not use the [`ask_password` function](https://github.com/abrt/libreport/blob/master/src/client-python/reportclient/clientmodule.c#L28) from the reportclient module?

**Comment by msrb** [comment]
> Why not use the [ask_password function](https://github.com/abrt/libreport/blob/master/src/client-python/reportclient/clientmodule.c#L28) from the reportclient module?

Well, that's a good point. We don't use those bindings in the current reporter-bugzilla implementation. We only depend on satyr for low level stuff. This would be the only dependency on the old libreport C code and I'd prefer to avoid that, if possible.

**Comment by michalfabik** [comment]
Looks fine to me.

**Comment by mvollmer** [comment]
Thanks! This works, but there are still messages from getpass delivered with the Progress signal:

```
# python3 /var/tmp/BUG.py
/org/freedesktop/reportd/Task
PROGRESS Generating backtrace
PROGRESS Backtrace is generated and saved, 14455 bytes
PROMPT API key is not provided by configuration. Please enter the API key for 'https://bugzilla.redhat.com': 
PROGRESS /usr/lib64/python3.11/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
PROGRESS   passwd = fallback_getpass(prompt, stream)
PROGRESS Warning: Password input may be echoed.
PROGRESS Password: 
...
```

This is mostly harmless, I guess, but a bit ugly.

**Pull request merged**
