### PR TITLE
RHEL7: attach the URL of the uploaded problem data to the relevant micro-report

### PR DESCRIPTION
**Pull request by mhabrnal**
After review I am going to squash the commits and going to add bugzilla's id into commit's comment.

Resolves: rhbz#1300780

### CODE REVIEW

**Comment by jfilak** [comment]
You forgot to add iso_date.at to one of these commits.

**Comment by jfilak** [comment]
I tried to build this pull-request wit iso_date.at and tests from https://github.com/abrt/abrt/pull/1109 finished successfully.

**Comment by mhabrnal** [comment]
I've added iso_date.at file and updated the pull request.

**Comment by jfilak** [comment]
Thank you! I built the pull-request and tried to report a crash. I didn't find any problem.

**Pull request merged**
