### PR TITLE
Strata → Hydra

### PR DESCRIPTION
**Pull request by ernestask**
See commits.

### CODE REVIEW

**Comment by mkutlak** [comment]
This should be backported to RHEL, right?

**Comment by ernestask** [comment]
Ah, now I remember why I had it as a draft at first. It should be backported, yes, but Hydra isn’t live yet, so we can wait around a bit.

**Comment by ernestask** [comment]
But there are some staging deployments for testing.

**Comment by mkutlak** [comment]
What about the `...rs/telemetry/abrt`?

https://github.com/abrt/libreport/blob/fa0c48f32c561929691cb3b77254f3ec5b9a58f4/src/plugins/reporter-rhtsupport.c#L381

**Comment by ernestask** [comment]
Oh, yes, that, too. I already complained to the people doing the migration. The idea was that they would drop the endpoint and wait for someone to complain. I complained beforehand, they wanted some information about what it’s for. Not quite sure what the outcome will be.

**Pull request closed without merging**
