### PR TITLE
Converting README to markdown (README.md)

### PR DESCRIPTION
**Pull request by TechMarinerh**
Converting README to markdown and  updating references in libreport.spec.in

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by mkutlak** [comment]
You forgot to add the README.md file to the Makefile.

**Comment by marusak** [comment]
> You forgot to add the README.md file to the Makefile.

great work @mkutlak! I think somebody should always test EACH AND EVERY PR before the PR gets merged. That way we can omit such stupid bugs.

@xsuchy wouldn't that be a preferred way? Always assign reviewer who tests the changes, proofreads and try building that. I've feeling that we merge PR just by looking at them and not really testing them.

**Comment by xsuchy** [comment]
> You forgot to add the README.md file to the Makefile.

??? There is no mention of README in Makefile. Which change you are speaking about?

**Comment by jfilak** [comment]
> ??? There is no mention of README in Makefile. Which change you are speaking about?

Automake expects README, so if you rename it to README.md, you have to make Automake aware of it:
https://github.com/abrt/abrt/commit/0020bf80cda35ee0ce0ecf91023f3abcc1c4d26d

**Comment by jfilak** [comment]
Anyway, you would notice if you tried to build the rpm package. By the way, what has happened to the PR builder?

**Comment by jfilak** [comment]
https://github.com/abrt/abrt/blob/master/abrt.spec.in#L787

**Comment by jfilak** [comment]
https://github.com/abrt/libreport/blob/master/libreport.spec.in#L444

**Comment by jfilak** [comment]
https://github.com/abrt/abrt/commit/0020bf80cda35ee0ce0ecf91023f3abcc1c4d26d#diff-c949f93d03f44a4217d7a138f9e2e54aR39

**Comment by mhabrnal** [comment]
@jfilak looks like the builder was not able to do the build because @TechMarinerh in not listed in white list.

**Pull request merged**
