### PR TITLE
Update German translation: sensitive

### PR DESCRIPTION
**Pull request by genodeftest**
"sensitiv" is a word in German, but it has a different meaning than "sensitive in English.

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by jfilak** [comment]
Thank you for the pull request. Unfortunately I cannot merge it because we maintain translations in [fedora.zanata.org](https://fedora.zanata.org/iteration/view/libreport/master?dswid=8624). Could you please do your changes to the translation files there? If you don't have time or you don't want to log in to Zanata, I will take care of it.

I apologize for the inconvenience. We will create contributing guidelines to not waste contributor's time anymore.

**Comment by genodeftest** [comment]
After selecting the project in zanata, I am on https://fedora.zanata.org/webtrans/translate?project=libreport&iteration=master&localeId=de&locale=en-US&dswid=-7315#view:doc;doc:libreport;search:sensitive;untranslated:show;fuzzy:show;translated:show;approved:show;rejected:show . I can't edit any content. Do you know why?

Top left shows a red lock with this tooltip: "This project version is readonly. It cannot be edited."

**Comment by xsuchy** [comment]
@genodeftest can you use this link? https://fedora.zanata.org/webtrans/translate?project=libreport&iteration=master&localeId=de&locale=en-US&dswid=6858#view%3Adoc;doc%3Alibreport
I am not sure how you get your link - it does not work for me.

**Comment by genodeftest** [comment]
@xsuchy still unable to do so, still seeing the same issue:

> Top left shows a red lock with this tooltip: "This project version is readonly. It cannot be edited."

And if I use the alpha editor, saving any string immediately undoes the change.

**Comment by xsuchy** [comment]
It seems there is some problem with ZANATA. Reported as https://zanata.atlassian.net/browse/ZNTA-1719

**Comment by genodeftest** [comment]
@xsuchy according to zanata, this is not a problem with zanata, but a configuration (setting) by the libreport project at zanata.

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by genodeftest** [comment]
Can you please fix the zanata configuration?

> It seems there is some problem with ZANATA. Reported as https://zanata.atlassian.net/browse/ZNTA-1719

They say it is not a bug but something you can fix by configuration.

**Comment by genodeftest** [comment]
Does one need special permissions to contribute?

**Comment by jfilak** [comment]
@genodeftest Seems that the libreport zanata project is already writable (perhaps @xsuchy did the change). Now you just need a fedora account to log into fedora.zanata.org (you can join the translators team : https://fedoraproject.org/wiki/L10N/Translate_on_Zanata , but I sometimes do translations to czech in other projects and I didn't do the steps on that page).

**Comment by xsuchy** [comment]
I updated strings in Zanata. It should be updated in git on next merge from Zanata.

**Comment by jfilak** [comment]
@xsuchy Thank you!

**Comment by genodeftest** [comment]
Thanks!

The reason why contributing translations does/did not work is that one needs to be member of the German translation group, which I am not (but requested access). I did not find this information anywhere on the fedora.zanata.org UI.

**Pull request closed without merging**
