### PR TITLE
wizard: Fix -Wincompatible-pointer-types

### PR DESCRIPTION
**Pull request by michalfabik**
See commit.

Signed-off-by: Michal Fabik <mfabik@redhat.com>

### CODE REVIEW

**Comment by mgrabovsky** [comment]
Where does this warnings pop up? I removed the `const`s in ce557c0f and noticed no warnings.

**Comment by michalfabik** [comment]
I get it just by running `make`:  

    $ ./autogen.sh && ./configure && make  
    ...  
    Making all in gui-wizard-gtk  
    make[3]: Entering directory '.../libreport/src/gui-wizard-gtk'  
      CC       report_gtk-wizard.o  
    wizard.c: In function ‘start_event_run’:  
    wizard.c:1756:27: warning: assignment to ‘void (*)(const char *, void *)’ from incompatible pointer type ‘void (*)(char *, void *)’ [-Wincompatible-pointer-types]  
     1756 |     state->error_callback = run_event_gtk_error;  
          |  

(Sorry, I got the warning type wrong in the title.)

**Comment by mgrabovsky** [comment]
Oh, right. In that case it should be enough to change the function signature and the type of `log_msg` can stay the same, right? (We need one fewer cast then.)

**Comment by michalfabik** [comment]
See now.

**Comment by mgrabovsky** [comment]
Ah, sorry, what I meant was to change the first argument of both `run_event_gtk_error()` and `update_command_run_log()` to be `const char *` as you did did in 4ec7114, but revert to `char *log_msg` on line 1400.

In the latest change, I'm slightly uncomfortable with casting a static string to a non-const `char *`.

**Review by mgrabovsky — APPROVED** [review]
Looks good.

**Pull request merged**
