### PR TITLE
Refined workflow for reporting to RHEL

### PR DESCRIPTION
**Pull request by mhabrnal**
Related: #1258474

### CODE REVIEW

**Comment by mhabrnal** [comment]
pull request updated

**Comment by jfilak** [comment]
I tested this pull request on Fedora Rawhide and I see both complex and simple details fields:
```
$ rpm -q libreport                                                                                                                                                        
libreport-2.6.4.13.g4093-1.fc24.x86_64
$ report-gtk -e report_Bugzilla -- /var/spool/abrt/ccpp-2016-03-03-12:53:22-17971
```

**Comment by mhabrnal** [comment]
I've updated pull request

**Comment by mhabrnal** [comment]
Added changes related to rhtsupport limited description issue rhbz#1261398.

**Pull request merged**
