### PR TITLE
Dump emergency analysis

### PR DESCRIPTION
**Pull request by michalfabik**
Remove the possibility to create and upload emergency reports when automatic reporting fails in `gnome-abrt`.

Remove related strings from l10n.  
  
Related: https://github.com/abrt/faf/pull/825, https://github.com/abrt/ansible-role-faf/pull/33, https://github.com/abrt/abrt-server-info-page/pull/7

### CODE REVIEW

**Comment by mkutlak** [comment]
These should be deleted too:

https://github.com/abrt/libreport/blob/861e8d10bcc40fffdd62cf3acff2923b07609730/src/gui-wizard-gtk/wizard.c#L1958

https://github.com/abrt/libreport/blob/861e8d10bcc40fffdd62cf3acff2923b07609730/src/gui-wizard-gtk/wizard.c#L1910

https://github.com/abrt/libreport/blob/861e8d10bcc40fffdd62cf3acff2923b07609730/src/gui-wizard-gtk/wizard.c#L3655

**Comment by michalfabik** [comment]
But I did already: https://github.com/abrt/libreport/pull/577/commits/844ba8e367f5be1869b9a4c88d5365b70a67ef5b ...?

**Comment by mkutlak** [comment]
Oh, sorry. I missed it in the big amout of translation file changes.

**Comment by michalfabik** [comment]
Those shouldn't have been changed at all, as I've just learned. Sorry about the confusion. I reverted the deletions.

**Comment by mkutlak** [comment]
LGTM

**Pull request merged**
